[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
# addopts = "--cov=tdd" # Line that add arguments to pytest but messes with VSCode debugger
testpaths=[
    "tests",
]